### ISSUE TITLE
index.html (Desktop) - Header and footer colors change depending on window size

### ISSUE THREAD

**Issue by CuriousDev165** [CuriousDev165/Moffat-Bay#20]
As pictured below, the desktop window's header and footer colors change depending on window size.

![Screenshot (109)](https://github.com/CuriousDev165/Moffat-Bay/assets/111553196/54e0c2e9-e25f-4523-9faa-799b45fcd276)
![Screenshot (110)](https://github.com/CuriousDev165/Moffat-Bay/assets/111553196/0e6d3b24-6bd9-4874-a591-4350a94f6257)

**Comment by J-Pedersen** [comment]
Since this was already explained in discord I am closing this issue.
For those that did not read the discord chat the backgrounds of the header and footer are color coded for different @media breakpoints for development and the actual backgrounds will be added after the template is complete.
