### ISSUE TITLE
Attempting to reserve a slip with no slips available opens a blank page

### ISSUE THREAD

**Issue by CuriousDev165** [CuriousDev165/Moffat-Bay#29]
Functionality is needed so that the user sees a notification, such as a pop-up, on the summary page that there is no slip currently available that fits their boat and is given an option to be added to a waitlist.

**Comment by J-Pedersen** [comment]
This issue is partially resolved. the waitlist function now exists and the reservation page does redirect to it properly.
however submitting a waitlist request does not work correctly.

**Comment by J-Pedersen** [comment]
this is fixed so i am closing it if there is an issue it can be reopened.
