### ISSUE TITLE
[M5] Create Database

### ISSUE THREAD

**Issue by CuriousDev165** [CuriousDev165/Moffat-Bay#9]
Using the ERD, create a MySQL database for the Moffat Bay project.

Ensure that the database and ERD match one another. If changes to the ERD are required, prepare a revised version for submission.

After creation, run a MySQL statement to show the contents (not the schema) of the table. Screenshot the results of each statement.

Leave a comment on this issue stating that you have tested the database connection in your dev environment and confirmed that the connection was successful.

Due Date: 8/27/2023 by 10:00 PM

**Comment by jakeives02** [comment]
Db Connection was successful!

**Comment by CuriousDev165** [comment]
Retest with Jacob's changes successful.

**Comment by J-Pedersen** [comment]
Tested. The dbinit, sql data insert and the db connection were all successful on my machine.

**Comment by scrandall93** [comment]
DB Connection was successful on my machine.

**Comment by jakeives02** [comment]
Still works!
